"""initial domain schema

Revision ID: 58f4778324a1
Revises: 
Create Date: 2026-10-07 16:16:36.426107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f4778324a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_config',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_phone_region', sa.String(length=2), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_language', sa.Enum('en', 'ar', name='business_language', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('weekly_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_hours_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('service_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('booking_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('handoff_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('greeting_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closing_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retention_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_business_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'ar', name='contact_preferred_language', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_contact_phone_e164_non_null', 'contact', ['phone_e164'], unique=True, postgresql_where=sa.text('phone_e164 IS NOT NULL'))
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_event_unpublished', 'outbox_event', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('provider_event_receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_provider_event_receipt_provider_external', 'provider_event_receipt', ['provider', 'external_event_id'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('bookable', sa.Boolean(), nullable=False),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('booking_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_duration_minutes > 0', name='ck_service_duration_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_service_code')
    )
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='booking_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(start_at IS NULL AND end_at IS NULL) OR (start_at IS NOT NULL AND end_at IS NOT NULL)', name='ck_booking_time_pair'),
    sa.CheckConstraint('(start_at IS NULL AND end_at IS NULL) OR start_at < end_at', name='ck_booking_time_order'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_contact_status', 'booking', ['contact_id', 'status'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('phone', 'whatsapp', name='conversation_channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='conversation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('control_mode', sa.Enum('ai', 'handoff_pending', 'human', name='conversation_control_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('language_mode', sa.Enum('unknown', 'en', 'ar', 'mixed', name='conversation_language_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('outcome', sa.Enum('information_only', 'booked', 'rescheduled', 'cancelled', 'handoff', 'unresolved', 'abandoned', name='conversation_outcome', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('recent_summary', sa.String(length=4000), nullable=True),
    sa.Column('pending_action_type', sa.Enum('create_booking', 'reschedule_booking', 'cancel_booking', name='pending_action_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('pending_action_status', sa.Enum('awaiting_confirmation', 'confirmed', name='pending_action_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('pending_action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_action_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_action_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_action_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(pending_action_type IS NULL AND pending_action_status IS NULL AND pending_action_payload IS NULL AND pending_action_created_at IS NULL AND pending_action_confirmed_at IS NULL AND pending_action_expires_at IS NULL) OR (pending_action_type IS NOT NULL AND pending_action_status IS NOT NULL AND pending_action_payload IS NOT NULL AND pending_action_created_at IS NOT NULL AND ((pending_action_status = 'confirmed' AND pending_action_confirmed_at IS NOT NULL) OR (pending_action_status = 'awaiting_confirmation' AND pending_action_confirmed_at IS NULL)))", name='ck_conversation_pending_action'),
    sa.CheckConstraint("(status = 'open' AND closed_at IS NULL) OR (status = 'closed' AND closed_at IS NOT NULL)", name='ck_conversation_close_time'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_contact_opened', 'conversation', ['contact_id', 'opened_at'], unique=False)
    op.create_index('ix_conversation_status_control_mode', 'conversation', ['status', 'control_mode'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'customer', 'assistant', 'human', 'provider', name='audit_actor_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=200), nullable=True),
    sa.Column('entity_identifier', sa.String(length=255), nullable=True),
    sa.Column('sanitized_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_conversation_occurred', 'audit_event', ['conversation_id', 'occurred_at'], unique=False)
    op.create_table('conversation_turn',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'assistant', 'human', 'system', name='conversation_turn_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language_mode', sa.Enum('unknown', 'en', 'ar', 'mixed', name='turn_language_mode', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_number > 0', name='ck_conversation_turn_sequence_positive'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_conversation_turn_sequence', 'conversation_turn', ['conversation_id', 'sequence_number'], unique=True)
    op.create_table('handoff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'resolved', 'cancelled', name='handoff_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Enum('explicit_request', 'repeated_misunderstanding', 'low_confidence', 'unknown_information', 'complaint', 'unusual_or_high_risk', 'urgent_or_emergency', 'integration_failure', 'cannot_safely_act', name='handoff_reason', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'high', 'urgent', name='handoff_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('safe_detail', sa.String(length=2000), nullable=True),
    sa.Column('safe_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_handoff_status_priority_requested', 'handoff', ['status', 'priority', 'requested_at'], unique=False)
    op.create_index('uq_handoff_active_conversation', 'handoff', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'accepted')"))
    op.create_table('tool_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'rejected', name='tool_execution_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('sanitized_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sanitized_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safe_error_code', sa.String(length=100), nullable=True),
    sa.Column('safe_error_message', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_execution_conversation', 'tool_execution', ['conversation_id'], unique=False)
    op.create_index('uq_tool_execution_idempotency_key_non_null', 'tool_execution', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tool_execution_idempotency_key_non_null', table_name='tool_execution', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_tool_execution_conversation', table_name='tool_execution')
    op.drop_table('tool_execution')
    op.drop_index('uq_handoff_active_conversation', table_name='handoff', postgresql_where=sa.text("status IN ('pending', 'accepted')"))
    op.drop_index('ix_handoff_status_priority_requested', table_name='handoff')
    op.drop_table('handoff')
    op.drop_index('uq_conversation_turn_sequence', table_name='conversation_turn')
    op.drop_table('conversation_turn')
    op.drop_index('ix_audit_event_conversation_occurred', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('ix_conversation_status_control_mode', table_name='conversation')
    op.drop_index('ix_conversation_contact_opened', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('ix_booking_contact_status', table_name='booking')
    op.drop_table('booking')
    op.drop_table('service')
    op.drop_index('uq_provider_event_receipt_provider_external', table_name='provider_event_receipt')
    op.drop_table('provider_event_receipt')
    op.drop_index('ix_outbox_event_unpublished', table_name='outbox_event', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox_event')
    op.drop_index('uq_contact_phone_e164_non_null', table_name='contact', postgresql_where=sa.text('phone_e164 IS NOT NULL'))
    op.drop_table('contact')
    op.drop_table('business_config')
    # ### end Alembic commands ###
