"""add Calendar references to Booking

Revision ID: e8b5d9e0d0c1
Revises: 58f4778324a1
Create Date: 2026-10-07 22:17:56.365314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b5d9e0d0c1'
down_revision: Union[str, None] = '58f4778324a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('calendar_id', sa.String(length=255), nullable=True))
    op.add_column('booking', sa.Column('calendar_event_id', sa.String(length=255), nullable=True))
    op.create_check_constraint(
        'ck_booking_calendar_reference_pair',
        'booking',
        '(calendar_id IS NULL AND calendar_event_id IS NULL) OR '
        '(calendar_id IS NOT NULL AND calendar_event_id IS NOT NULL)',
    )
    op.create_check_constraint(
        'ck_booking_confirmed_calendar_reference',
        'booking',
        "status <> 'confirmed' OR "
        "(status = 'confirmed' AND calendar_id IS NOT NULL AND calendar_event_id IS NOT NULL)",
    )
    op.create_index('uq_booking_calendar_event', 'booking', ['calendar_id', 'calendar_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_booking_calendar_event', table_name='booking')
    op.drop_constraint('ck_booking_confirmed_calendar_reference', 'booking', type_='check')
    op.drop_constraint('ck_booking_calendar_reference_pair', 'booking', type_='check')
    op.drop_column('booking', 'calendar_event_id')
    op.drop_column('booking', 'calendar_id')
    # ### end Alembic commands ###
